Automated classification of heart disease is an important task that can assist doctors and technologist in thier screeing process. Recently, various ML models have been adopted or adopted in order to complete the task.

In [1]:
import pandas as pd


In [2]:
data = pd.read_csv("heart.csv")

In [3]:
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [4]:
X = data.drop('output',axis = 1)

In [5]:
X

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2  
2      0      2  
3      0      2  
4      0      2  
..   ...    ...  
298    0      3  
299    0      3  
300    2      3  
301    1      3  
302    1      2  

[303 rows x 13 columns]

In [6]:
y = data["output"]

In [7]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split


In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2,random_state=50)

In [10]:
xtrain.shape

(242, 13)

In [11]:
xtest.shape

(61, 13)

In [13]:
from tensorflow.keras.models import Sequential

In [14]:
model = Sequential() #BRAIN WITHOUT NEURON

In [15]:
from tensorflow.keras.layers import Dense


In [17]:
model.add(Dense(100, activation="relu",input_shape = (13,))) #input layer

In [18]:
model.add(Dense(200, activation="relu")) #hidden layer
model.add(Dense(300, activation="relu")) #hidden layer
model.add(Dense(200, activation="relu")) #hidden layer
model.add(Dense(400, activation="relu")) #hidden layer

In [19]:
model.add(Dense(1, activation="sigmoid"))

In [20]:
model.compile(optimizer="adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [21]:
model.fit(xtrain,ytrain,epochs = 100, batch_size=10)

Epoch 1/100
25/25 [==============================] - 3s 28ms/step - loss: 1.4210 - accuracy: 0.5496
Epoch 2/100
25/25 [==============================] - 0s 11ms/step - loss: 0.6510 - accuracy: 0.6529
Epoch 3/100
25/25 [==============================] - 0s 10ms/step - loss: 0.6672 - accuracy: 0.6116
Epoch 4/100
25/25 [==============================] - 0s 7ms/step - loss: 0.6392 - accuracy: 0.6860
Epoch 5/100
25/25 [==============================] - 0s 14ms/step - loss: 0.6187 - accuracy: 0.6694
Epoch 6/100
25/25 [==============================] - 0s 7ms/step - loss: 0.6424 - accuracy: 0.6405
Epoch 7/100
25/25 [==============================] - 0s 11ms/step - loss: 0.6118 - accuracy: 0.6570
Epoch 8/100
25/25 [==============================] - 0s 9ms/step - loss: 0.6337 - accuracy: 0.6364
Epoch 9/100
25/25 [==============================] - 0s 6ms/step - loss: 0.5987 - accuracy: 0.6446
Epoch 10/100
25/25 [==============================] - 0s 6ms/step - loss: 0.6564 - accuracy: 0.6322
Epoc

In [22]:
ypred = model.predict(xtest)

2/2 [==============================] - 0s 3ms/step


In [26]:
ypred

array([[0.92216074],
       [0.77761763],
       [0.40042138],
       [0.8389657 ],
       [0.8066104 ],
       [0.03976227],
       [0.03363429],
       [0.67841685],
       [0.15371749],
       [0.89849466],
       [0.8741814 ],
       [0.68054265],
       [0.7440806 ],
       [0.5337187 ],
       [0.74189216],
       [0.67549103],
       [0.6379268 ],
       [0.7150783 ],
       [0.13752955],
       [0.79319006],
       [0.5417226 ],
       [0.03392399],
       [0.99683267],
       [0.77254266],
       [0.9884611 ],
       [0.9014933 ],
       [0.9928939 ],
       [0.00571295],
       [0.9781927 ],
       [0.04908545],
       [0.02375471],
       [0.11472223],
       [0.97532827],
       [0.48143414],
       [0.25381336],
       [0.23265785],
       [0.69329476],
       [0.17252435],
       [0.96137947],
       [0.9840077 ],
       [0.9020309 ],
       [0.8876946 ],
       [0.40360573],
       [0.1181221 ],
       [0.89156234],
       [0.5512768 ],
       [0.65133137],
       [0.757

In [27]:
ypred_transformed = []
for i in ypred:
    if i >= 0.5:
        ypred_transformed.append([1])
    else:
        ypred_transformed.append([0])

In [28]:
ypred_transformed 

[[1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1]]

In [29]:
import numpy as np
ypred_transformed = np.array(ypred_transformed)

In [30]:
ypred_transformed

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1]])

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ypred_transformed,ytest)

array([[17,  4],
       [ 8, 32]], dtype=int64)

In [ ]:
[tp,fp
fn,tn]

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(ypred_transformed,ytest)

0.8032786885245902